// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClient(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddClient'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AppBrowse(arg1, arg2) {
  return window['go']['main']['App']['AppBrowse'](arg1, arg2);
}

export function DisconnectClient(arg1) {
  return window['go']['main']['App']['DisconnectClient'](arg1);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function ReconnectClient(arg1) {
  return window['go']['main']['App']['ReconnectClient'](arg1);
}
