// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClient(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddClient'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AppBrowse(arg1, arg2) {
  return window['go']['main']['App']['AppBrowse'](arg1, arg2);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function DisconnectClient(arg1) {
  return window['go']['main']['App']['DisconnectClient'](arg1);
}

export function DropClient(arg1) {
  return window['go']['main']['App']['DropClient'](arg1);
}

export function ExportBrowseSelection(arg1, arg2) {
  return window['go']['main']['App']['ExportBrowseSelection'](arg1, arg2);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetServiceInfo(arg1) {
  return window['go']['main']['App']['GetServiceInfo'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetTimeSeries(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTimeSeries'](arg1, arg2, arg3, arg4, arg5);
}

export function GetUniqueEntries(arg1, arg2) {
  return window['go']['main']['App']['GetUniqueEntries'](arg1, arg2);
}

export function LoadConfigFromFile() {
  return window['go']['main']['App']['LoadConfigFromFile']();
}

export function ReconnectClient(arg1) {
  return window['go']['main']['App']['ReconnectClient'](arg1);
}

export function SaveConfigToFile(arg1) {
  return window['go']['main']['App']['SaveConfigToFile'](arg1);
}

export function SaveResultsAsCSV(arg1) {
  return window['go']['main']['App']['SaveResultsAsCSV'](arg1);
}

export function SetupLoggingService(arg1) {
  return window['go']['main']['App']['SetupLoggingService'](arg1);
}

export function StartMonitor(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartMonitor'](arg1, arg2, arg3);
}

export function StopMonitor(arg1) {
  return window['go']['main']['App']['StopMonitor'](arg1);
}

export function ToggleService(arg1, arg2) {
  return window['go']['main']['App']['ToggleService'](arg1, arg2);
}
