// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {machine} from '../models';

export function AddClient(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<number>;

export function AppBrowse(arg1:number,arg2:string):Promise<Array<machine.BrowseResult>>;

export function DisconnectClient(arg1:number):Promise<void>;

export function DropClient(arg1:number):Promise<boolean>;

export function ExportBrowseSelection(arg1:string,arg2:string):Promise<string>;

export function GetClients():Promise<Array<machine.ClientInfos>>;

export function LoadConfigFromFile():Promise<string>;

export function ReconnectClient(arg1:number):Promise<void>;

export function SaveConfigToFile(arg1:string):Promise<string>;

export function SetupLoggingService():Promise<void>;

export function StartMonitor(arg1:number,arg2:number,arg3:Array<string>):Promise<boolean>;

export function StopMonitor(arg1:number):Promise<boolean>;
